/********************************************************************************
** Form generated from reading UI file 'Deck_builder.ui'
**
** Created by: Qt User Interface Compiler version 5.10.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_DECK_BUILDER_H
#define UI_DECK_BUILDER_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QScrollArea>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Deck_builderClass
{
public:
    QAction *openButton;
    QAction *saveButton;
    QAction *actiontest;
    QWidget *centralWidget;
    QGroupBox *proposalsBox;
    QScrollArea *proposalsArea;
    QWidget *scrollAreaWidgetContents;
    QGroupBox *deckBox;
    QScrollArea *deckArea;
    QWidget *scrollAreaWidgetContents_2;
    QGroupBox *menuBox;
    QPushButton *openConfigButton;
    QPushButton *initiateButton;
    QPushButton *openDeckButton;
    QPushButton *resetDeckButton;
    QPushButton *resetGraphButton;
    QPushButton *saveDeckButton;
    QGroupBox *statsBox;
    QGroupBox *colorBox;
    QLabel *whiteLabel;
    QLabel *blueLabel;
    QLabel *blackLabel;
    QLabel *greenLabel;
    QLabel *redLabel;
    QLabel *whiteU;
    QLabel *whitePercent;
    QLabel *bluePercent;
    QLabel *blackPercent;
    QLabel *redPercent;
    QLabel *greenU;
    QLabel *redU;
    QLabel *blackU;
    QLabel *blueU;
    QLabel *greenPercent;
    QLabel *whiteU_2;
    QLabel *whiteU_3;
    QLabel *whiteU_4;
    QLabel *whiteU_5;
    QLabel *whiteU_6;
    QGroupBox *repartBox;
    QLabel *spellsLabel;
    QLabel *creaturesLabel;
    QLabel *whiteU_7;
    QLabel *whiteU_8;
    QLabel *creaturesPercent;
    QLabel *creaturesU;
    QLabel *spellsU;
    QLabel *spellsPercent;
    QGroupBox *manaBox;
    QLabel *manaAverageLabel;
    QLabel *manaU;
    QGroupBox *configBox;
    QLabel *mana;
    QLabel *creaturesPartLabel;
    QLabel *creaturesPartPercent;
    QLabel *nbColorsLabel;
    QLabel *manaLabel;
    QLabel *spellsPartLabel;
    QLabel *spellsPart;
    QLabel *spellPercentLabel;
    QLabel *creaturesPart;
    QLabel *nbColors;

    void setupUi(QMainWindow *Deck_builderClass)
    {
        if (Deck_builderClass->objectName().isEmpty())
            Deck_builderClass->setObjectName(QStringLiteral("Deck_builderClass"));
        Deck_builderClass->setEnabled(true);
        Deck_builderClass->resize(1920, 1080);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(Deck_builderClass->sizePolicy().hasHeightForWidth());
        Deck_builderClass->setSizePolicy(sizePolicy);
        Deck_builderClass->setMinimumSize(QSize(1920, 1080));
        Deck_builderClass->setMaximumSize(QSize(1920, 1080));
        QFont font;
        font.setPointSize(14);
        Deck_builderClass->setFont(font);
        openButton = new QAction(Deck_builderClass);
        openButton->setObjectName(QStringLiteral("openButton"));
        saveButton = new QAction(Deck_builderClass);
        saveButton->setObjectName(QStringLiteral("saveButton"));
        actiontest = new QAction(Deck_builderClass);
        actiontest->setObjectName(QStringLiteral("actiontest"));
        centralWidget = new QWidget(Deck_builderClass);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        proposalsBox = new QGroupBox(centralWidget);
        proposalsBox->setObjectName(QStringLiteral("proposalsBox"));
        proposalsBox->setGeometry(QRect(200, 0, 1720, 455));
        sizePolicy.setHeightForWidth(proposalsBox->sizePolicy().hasHeightForWidth());
        proposalsBox->setSizePolicy(sizePolicy);
        QFont font1;
        font1.setPointSize(16);
        proposalsBox->setFont(font1);
        proposalsBox->setAutoFillBackground(false);
        proposalsArea = new QScrollArea(proposalsBox);
        proposalsArea->setObjectName(QStringLiteral("proposalsArea"));
        proposalsArea->setGeometry(QRect(0, 30, 1720, 415));
        sizePolicy.setHeightForWidth(proposalsArea->sizePolicy().hasHeightForWidth());
        proposalsArea->setSizePolicy(sizePolicy);
        proposalsArea->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        proposalsArea->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        proposalsArea->setWidgetResizable(true);
        scrollAreaWidgetContents = new QWidget();
        scrollAreaWidgetContents->setObjectName(QStringLiteral("scrollAreaWidgetContents"));
        scrollAreaWidgetContents->setGeometry(QRect(0, 0, 1718, 392));
        proposalsArea->setWidget(scrollAreaWidgetContents);
        deckBox = new QGroupBox(centralWidget);
        deckBox->setObjectName(QStringLiteral("deckBox"));
        deckBox->setGeometry(QRect(200, 455, 1720, 614));
        deckBox->setFont(font1);
        deckBox->setAutoFillBackground(false);
        deckArea = new QScrollArea(deckBox);
        deckArea->setObjectName(QStringLiteral("deckArea"));
        deckArea->setGeometry(QRect(0, 50, 1720, 564));
        deckArea->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        deckArea->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        deckArea->setWidgetResizable(true);
        scrollAreaWidgetContents_2 = new QWidget();
        scrollAreaWidgetContents_2->setObjectName(QStringLiteral("scrollAreaWidgetContents_2"));
        scrollAreaWidgetContents_2->setGeometry(QRect(0, 0, 1697, 562));
        deckArea->setWidget(scrollAreaWidgetContents_2);
        menuBox = new QGroupBox(centralWidget);
        menuBox->setObjectName(QStringLiteral("menuBox"));
        menuBox->setGeometry(QRect(0, 0, 200, 410));
        menuBox->setFont(font);
        menuBox->setAutoFillBackground(true);
        openConfigButton = new QPushButton(menuBox);
        openConfigButton->setObjectName(QStringLiteral("openConfigButton"));
        openConfigButton->setGeometry(QRect(20, 40, 160, 40));
        QFont font2;
        font2.setPointSize(12);
        openConfigButton->setFont(font2);
        initiateButton = new QPushButton(menuBox);
        initiateButton->setObjectName(QStringLiteral("initiateButton"));
        initiateButton->setGeometry(QRect(20, 100, 160, 40));
        initiateButton->setFont(font2);
        openDeckButton = new QPushButton(menuBox);
        openDeckButton->setObjectName(QStringLiteral("openDeckButton"));
        openDeckButton->setGeometry(QRect(20, 160, 160, 40));
        openDeckButton->setFont(font2);
        resetDeckButton = new QPushButton(menuBox);
        resetDeckButton->setObjectName(QStringLiteral("resetDeckButton"));
        resetDeckButton->setGeometry(QRect(20, 280, 160, 40));
        resetDeckButton->setFont(font2);
        resetGraphButton = new QPushButton(menuBox);
        resetGraphButton->setObjectName(QStringLiteral("resetGraphButton"));
        resetGraphButton->setGeometry(QRect(20, 340, 160, 40));
        resetGraphButton->setFont(font2);
        saveDeckButton = new QPushButton(menuBox);
        saveDeckButton->setObjectName(QStringLiteral("saveDeckButton"));
        saveDeckButton->setGeometry(QRect(20, 220, 160, 40));
        QFont font3;
        font3.setPointSize(11);
        saveDeckButton->setFont(font3);
        statsBox = new QGroupBox(centralWidget);
        statsBox->setObjectName(QStringLiteral("statsBox"));
        statsBox->setGeometry(QRect(0, 610, 200, 360));
        statsBox->setFont(font);
        statsBox->setAutoFillBackground(true);
        colorBox = new QGroupBox(statsBox);
        colorBox->setObjectName(QStringLiteral("colorBox"));
        colorBox->setGeometry(QRect(10, 30, 180, 180));
        colorBox->setFont(font2);
        colorBox->setAutoFillBackground(true);
        whiteLabel = new QLabel(colorBox);
        whiteLabel->setObjectName(QStringLiteral("whiteLabel"));
        whiteLabel->setGeometry(QRect(20, 20, 60, 30));
        QFont font4;
        font4.setPointSize(10);
        whiteLabel->setFont(font4);
        whiteLabel->setFrameShadow(QFrame::Sunken);
        blueLabel = new QLabel(colorBox);
        blueLabel->setObjectName(QStringLiteral("blueLabel"));
        blueLabel->setGeometry(QRect(20, 50, 60, 30));
        blueLabel->setFont(font4);
        blackLabel = new QLabel(colorBox);
        blackLabel->setObjectName(QStringLiteral("blackLabel"));
        blackLabel->setGeometry(QRect(20, 80, 60, 30));
        blackLabel->setFont(font4);
        greenLabel = new QLabel(colorBox);
        greenLabel->setObjectName(QStringLiteral("greenLabel"));
        greenLabel->setGeometry(QRect(20, 140, 60, 30));
        greenLabel->setFont(font4);
        redLabel = new QLabel(colorBox);
        redLabel->setObjectName(QStringLiteral("redLabel"));
        redLabel->setGeometry(QRect(20, 110, 60, 30));
        redLabel->setFont(font4);
        whiteU = new QLabel(colorBox);
        whiteU->setObjectName(QStringLiteral("whiteU"));
        whiteU->setGeometry(QRect(90, 20, 30, 30));
        whiteU->setFont(font4);
        whiteU->setAlignment(Qt::AlignCenter);
        whitePercent = new QLabel(colorBox);
        whitePercent->setObjectName(QStringLiteral("whitePercent"));
        whitePercent->setGeometry(QRect(130, 20, 30, 30));
        whitePercent->setFont(font4);
        whitePercent->setAlignment(Qt::AlignCenter);
        bluePercent = new QLabel(colorBox);
        bluePercent->setObjectName(QStringLiteral("bluePercent"));
        bluePercent->setGeometry(QRect(130, 50, 30, 30));
        bluePercent->setFont(font4);
        bluePercent->setAlignment(Qt::AlignCenter);
        blackPercent = new QLabel(colorBox);
        blackPercent->setObjectName(QStringLiteral("blackPercent"));
        blackPercent->setGeometry(QRect(130, 80, 30, 30));
        blackPercent->setFont(font4);
        blackPercent->setAlignment(Qt::AlignCenter);
        redPercent = new QLabel(colorBox);
        redPercent->setObjectName(QStringLiteral("redPercent"));
        redPercent->setGeometry(QRect(130, 110, 30, 30));
        redPercent->setFont(font4);
        redPercent->setAlignment(Qt::AlignCenter);
        greenU = new QLabel(colorBox);
        greenU->setObjectName(QStringLiteral("greenU"));
        greenU->setGeometry(QRect(90, 140, 30, 30));
        greenU->setFont(font4);
        greenU->setAlignment(Qt::AlignCenter);
        redU = new QLabel(colorBox);
        redU->setObjectName(QStringLiteral("redU"));
        redU->setGeometry(QRect(90, 110, 30, 30));
        redU->setFont(font4);
        redU->setAlignment(Qt::AlignCenter);
        blackU = new QLabel(colorBox);
        blackU->setObjectName(QStringLiteral("blackU"));
        blackU->setGeometry(QRect(90, 80, 30, 30));
        blackU->setFont(font4);
        blackU->setAlignment(Qt::AlignCenter);
        blueU = new QLabel(colorBox);
        blueU->setObjectName(QStringLiteral("blueU"));
        blueU->setGeometry(QRect(90, 50, 30, 30));
        blueU->setFont(font4);
        blueU->setAlignment(Qt::AlignCenter);
        greenPercent = new QLabel(colorBox);
        greenPercent->setObjectName(QStringLiteral("greenPercent"));
        greenPercent->setGeometry(QRect(130, 140, 30, 30));
        greenPercent->setFont(font4);
        greenPercent->setAlignment(Qt::AlignCenter);
        whiteU_2 = new QLabel(colorBox);
        whiteU_2->setObjectName(QStringLiteral("whiteU_2"));
        whiteU_2->setGeometry(QRect(160, 80, 20, 30));
        whiteU_2->setFont(font4);
        whiteU_2->setAlignment(Qt::AlignCenter);
        whiteU_3 = new QLabel(colorBox);
        whiteU_3->setObjectName(QStringLiteral("whiteU_3"));
        whiteU_3->setGeometry(QRect(160, 110, 20, 30));
        whiteU_3->setFont(font4);
        whiteU_3->setAlignment(Qt::AlignCenter);
        whiteU_4 = new QLabel(colorBox);
        whiteU_4->setObjectName(QStringLiteral("whiteU_4"));
        whiteU_4->setGeometry(QRect(160, 140, 20, 30));
        whiteU_4->setFont(font4);
        whiteU_4->setAlignment(Qt::AlignCenter);
        whiteU_5 = new QLabel(colorBox);
        whiteU_5->setObjectName(QStringLiteral("whiteU_5"));
        whiteU_5->setGeometry(QRect(160, 20, 20, 30));
        whiteU_5->setFont(font4);
        whiteU_5->setAlignment(Qt::AlignCenter);
        whiteU_6 = new QLabel(colorBox);
        whiteU_6->setObjectName(QStringLiteral("whiteU_6"));
        whiteU_6->setGeometry(QRect(160, 50, 20, 30));
        whiteU_6->setFont(font4);
        whiteU_6->setAlignment(Qt::AlignCenter);
        repartBox = new QGroupBox(statsBox);
        repartBox->setObjectName(QStringLiteral("repartBox"));
        repartBox->setGeometry(QRect(10, 210, 180, 90));
        repartBox->setFont(font2);
        repartBox->setAutoFillBackground(true);
        spellsLabel = new QLabel(repartBox);
        spellsLabel->setObjectName(QStringLiteral("spellsLabel"));
        spellsLabel->setGeometry(QRect(20, 50, 60, 30));
        spellsLabel->setFont(font4);
        creaturesLabel = new QLabel(repartBox);
        creaturesLabel->setObjectName(QStringLiteral("creaturesLabel"));
        creaturesLabel->setGeometry(QRect(20, 20, 60, 30));
        QFont font5;
        font5.setPointSize(9);
        creaturesLabel->setFont(font5);
        whiteU_7 = new QLabel(repartBox);
        whiteU_7->setObjectName(QStringLiteral("whiteU_7"));
        whiteU_7->setGeometry(QRect(160, 50, 20, 30));
        whiteU_7->setFont(font4);
        whiteU_7->setAlignment(Qt::AlignCenter);
        whiteU_8 = new QLabel(repartBox);
        whiteU_8->setObjectName(QStringLiteral("whiteU_8"));
        whiteU_8->setGeometry(QRect(160, 20, 20, 30));
        whiteU_8->setFont(font4);
        whiteU_8->setAlignment(Qt::AlignCenter);
        creaturesPercent = new QLabel(repartBox);
        creaturesPercent->setObjectName(QStringLiteral("creaturesPercent"));
        creaturesPercent->setGeometry(QRect(130, 20, 30, 30));
        creaturesPercent->setFont(font4);
        creaturesPercent->setAlignment(Qt::AlignCenter);
        creaturesU = new QLabel(repartBox);
        creaturesU->setObjectName(QStringLiteral("creaturesU"));
        creaturesU->setGeometry(QRect(90, 20, 30, 30));
        creaturesU->setFont(font4);
        creaturesU->setAlignment(Qt::AlignCenter);
        spellsU = new QLabel(repartBox);
        spellsU->setObjectName(QStringLiteral("spellsU"));
        spellsU->setGeometry(QRect(90, 50, 30, 30));
        spellsU->setFont(font4);
        spellsU->setAlignment(Qt::AlignCenter);
        spellsPercent = new QLabel(repartBox);
        spellsPercent->setObjectName(QStringLiteral("spellsPercent"));
        spellsPercent->setGeometry(QRect(130, 50, 30, 30));
        spellsPercent->setFont(font4);
        spellsPercent->setAlignment(Qt::AlignCenter);
        manaBox = new QGroupBox(statsBox);
        manaBox->setObjectName(QStringLiteral("manaBox"));
        manaBox->setGeometry(QRect(10, 300, 180, 60));
        manaBox->setFont(font2);
        manaBox->setAutoFillBackground(true);
        manaAverageLabel = new QLabel(manaBox);
        manaAverageLabel->setObjectName(QStringLiteral("manaAverageLabel"));
        manaAverageLabel->setGeometry(QRect(20, 20, 80, 30));
        manaAverageLabel->setFont(font4);
        manaU = new QLabel(manaBox);
        manaU->setObjectName(QStringLiteral("manaU"));
        manaU->setGeometry(QRect(120, 20, 30, 30));
        manaU->setFont(font4);
        manaU->setAlignment(Qt::AlignCenter);
        configBox = new QGroupBox(centralWidget);
        configBox->setObjectName(QStringLiteral("configBox"));
        configBox->setGeometry(QRect(0, 410, 200, 200));
        configBox->setFont(font);
        configBox->setAutoFillBackground(true);
        mana = new QLabel(configBox);
        mana->setObjectName(QStringLiteral("mana"));
        mana->setGeometry(QRect(120, 70, 40, 40));
        mana->setFont(font2);
        mana->setAlignment(Qt::AlignCenter);
        creaturesPartLabel = new QLabel(configBox);
        creaturesPartLabel->setObjectName(QStringLiteral("creaturesPartLabel"));
        creaturesPartLabel->setGeometry(QRect(20, 150, 100, 40));
        creaturesPartLabel->setFont(font2);
        creaturesPartPercent = new QLabel(configBox);
        creaturesPartPercent->setObjectName(QStringLiteral("creaturesPartPercent"));
        creaturesPartPercent->setGeometry(QRect(160, 150, 30, 40));
        creaturesPartPercent->setFont(font2);
        creaturesPartPercent->setAlignment(Qt::AlignCenter);
        nbColorsLabel = new QLabel(configBox);
        nbColorsLabel->setObjectName(QStringLiteral("nbColorsLabel"));
        nbColorsLabel->setGeometry(QRect(20, 30, 100, 40));
        nbColorsLabel->setFont(font2);
        nbColorsLabel->setFrameShadow(QFrame::Sunken);
        manaLabel = new QLabel(configBox);
        manaLabel->setObjectName(QStringLiteral("manaLabel"));
        manaLabel->setGeometry(QRect(20, 70, 100, 40));
        manaLabel->setFont(font2);
        spellsPartLabel = new QLabel(configBox);
        spellsPartLabel->setObjectName(QStringLiteral("spellsPartLabel"));
        spellsPartLabel->setGeometry(QRect(20, 110, 100, 40));
        spellsPartLabel->setFont(font2);
        spellsPart = new QLabel(configBox);
        spellsPart->setObjectName(QStringLiteral("spellsPart"));
        spellsPart->setGeometry(QRect(120, 110, 40, 40));
        spellsPart->setFont(font2);
        spellsPart->setAlignment(Qt::AlignCenter);
        spellPercentLabel = new QLabel(configBox);
        spellPercentLabel->setObjectName(QStringLiteral("spellPercentLabel"));
        spellPercentLabel->setGeometry(QRect(160, 110, 30, 40));
        spellPercentLabel->setFont(font2);
        spellPercentLabel->setAlignment(Qt::AlignCenter);
        creaturesPart = new QLabel(configBox);
        creaturesPart->setObjectName(QStringLiteral("creaturesPart"));
        creaturesPart->setGeometry(QRect(120, 150, 40, 40));
        creaturesPart->setFont(font2);
        creaturesPart->setAlignment(Qt::AlignCenter);
        nbColors = new QLabel(configBox);
        nbColors->setObjectName(QStringLiteral("nbColors"));
        nbColors->setGeometry(QRect(120, 30, 40, 40));
        nbColors->setFont(font2);
        nbColors->setAlignment(Qt::AlignCenter);
        Deck_builderClass->setCentralWidget(centralWidget);

        retranslateUi(Deck_builderClass);

        QMetaObject::connectSlotsByName(Deck_builderClass);
    } // setupUi

    void retranslateUi(QMainWindow *Deck_builderClass)
    {
        Deck_builderClass->setWindowTitle(QApplication::translate("Deck_builderClass", "Deck_builder", nullptr));
        openButton->setText(QApplication::translate("Deck_builderClass", "Ouvrir deck", nullptr));
        saveButton->setText(QApplication::translate("Deck_builderClass", "Sauvegarder deck", nullptr));
        actiontest->setText(QApplication::translate("Deck_builderClass", "test", nullptr));
        proposalsBox->setTitle(QApplication::translate("Deck_builderClass", "Propositions", nullptr));
        deckBox->setTitle(QApplication::translate("Deck_builderClass", "Deck", nullptr));
        menuBox->setTitle(QApplication::translate("Deck_builderClass", "Menu", nullptr));
        openConfigButton->setText(QApplication::translate("Deck_builderClass", "Ouvrir config", nullptr));
        initiateButton->setText(QApplication::translate("Deck_builderClass", "G\303\251n\303\251rer graphe", nullptr));
        openDeckButton->setText(QApplication::translate("Deck_builderClass", "Ouvrir deck", nullptr));
        resetDeckButton->setText(QApplication::translate("Deck_builderClass", "Reset deck", nullptr));
        resetGraphButton->setText(QApplication::translate("Deck_builderClass", "Reset graphe", nullptr));
        saveDeckButton->setText(QApplication::translate("Deck_builderClass", "Sauvegarder deck", nullptr));
        statsBox->setTitle(QApplication::translate("Deck_builderClass", "Statistiques", nullptr));
        colorBox->setTitle(QApplication::translate("Deck_builderClass", "Couleurs", nullptr));
        whiteLabel->setText(QApplication::translate("Deck_builderClass", "Blanc", nullptr));
        blueLabel->setText(QApplication::translate("Deck_builderClass", "Bleu", nullptr));
        blackLabel->setText(QApplication::translate("Deck_builderClass", "Noir", nullptr));
        greenLabel->setText(QApplication::translate("Deck_builderClass", "Vert", nullptr));
        redLabel->setText(QApplication::translate("Deck_builderClass", "Rouge", nullptr));
        whiteU->setText(QApplication::translate("Deck_builderClass", "0", nullptr));
        whitePercent->setText(QApplication::translate("Deck_builderClass", "0", nullptr));
        bluePercent->setText(QApplication::translate("Deck_builderClass", "0", nullptr));
        blackPercent->setText(QApplication::translate("Deck_builderClass", "0", nullptr));
        redPercent->setText(QApplication::translate("Deck_builderClass", "0", nullptr));
        greenU->setText(QApplication::translate("Deck_builderClass", "0", nullptr));
        redU->setText(QApplication::translate("Deck_builderClass", "0", nullptr));
        blackU->setText(QApplication::translate("Deck_builderClass", "0", nullptr));
        blueU->setText(QApplication::translate("Deck_builderClass", "0", nullptr));
        greenPercent->setText(QApplication::translate("Deck_builderClass", "0", nullptr));
        whiteU_2->setText(QApplication::translate("Deck_builderClass", "%", nullptr));
        whiteU_3->setText(QApplication::translate("Deck_builderClass", "%", nullptr));
        whiteU_4->setText(QApplication::translate("Deck_builderClass", "%", nullptr));
        whiteU_5->setText(QApplication::translate("Deck_builderClass", "%", nullptr));
        whiteU_6->setText(QApplication::translate("Deck_builderClass", "%", nullptr));
        repartBox->setTitle(QApplication::translate("Deck_builderClass", "R\303\251partition", nullptr));
        spellsLabel->setText(QApplication::translate("Deck_builderClass", "Sorts", nullptr));
        creaturesLabel->setText(QApplication::translate("Deck_builderClass", "Cr\303\251atures", nullptr));
        whiteU_7->setText(QApplication::translate("Deck_builderClass", "%", nullptr));
        whiteU_8->setText(QApplication::translate("Deck_builderClass", "%", nullptr));
        creaturesPercent->setText(QApplication::translate("Deck_builderClass", "0", nullptr));
        creaturesU->setText(QApplication::translate("Deck_builderClass", "0", nullptr));
        spellsU->setText(QApplication::translate("Deck_builderClass", "0", nullptr));
        spellsPercent->setText(QApplication::translate("Deck_builderClass", "0", nullptr));
        manaBox->setTitle(QApplication::translate("Deck_builderClass", "Co\303\273ts en mana", nullptr));
        manaAverageLabel->setText(QApplication::translate("Deck_builderClass", "Moyenne", nullptr));
        manaU->setText(QApplication::translate("Deck_builderClass", "0", nullptr));
        configBox->setTitle(QApplication::translate("Deck_builderClass", "Configuration", nullptr));
        mana->setText(QApplication::translate("Deck_builderClass", "0", nullptr));
        creaturesPartLabel->setText(QApplication::translate("Deck_builderClass", "Cr\303\251atures", nullptr));
        creaturesPartPercent->setText(QApplication::translate("Deck_builderClass", "%", nullptr));
        nbColorsLabel->setText(QApplication::translate("Deck_builderClass", "Couleurs", nullptr));
        manaLabel->setText(QApplication::translate("Deck_builderClass", "Mana", nullptr));
        spellsPartLabel->setText(QApplication::translate("Deck_builderClass", "Sorts", nullptr));
        spellsPart->setText(QApplication::translate("Deck_builderClass", "0", nullptr));
        spellPercentLabel->setText(QApplication::translate("Deck_builderClass", "%", nullptr));
        creaturesPart->setText(QApplication::translate("Deck_builderClass", "0", nullptr));
        nbColors->setText(QApplication::translate("Deck_builderClass", "0", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Deck_builderClass: public Ui_Deck_builderClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_DECK_BUILDER_H
